### ISSUE TITLE
BoschSHCBindingConstants.java - Auto-generated code

### ISSUE THREAD

**Issue by coeing** [stefan-kaestle/openhab2-addons#10]
BoschSHCBindingConstants.java tells me about auto-generated code, but I can't see how to trigger the auto-generation.

Would be nice to have a hint there or in the Readme.md how to trigger the auto-generation because I always edited the code myself for the last changes.

**Comment by GerdZanker** [comment]
I guess the ``parse-things.py`` from the ``org.openhab.binding.boschshc`` is used to generate the snippets manually and the output is copied & pasted into the ``BoschSHCBindingConstants.java``

**Comment by stefan-kaestle** [comment]
I don't remember what that thing is to be honest. Seems incomplete. 

Seems incomplete. Maybe you can just ignore that part :-P

**Comment by coeing** [comment]
Okay, should we throw it out? I had a look at the script and the idea is okay, but I think it is not worth the work because the channel constants won't change very often once they are in :)

**Comment by stefan-kaestle** [comment]
Yes, let's throw it out :-) I didn't even remember I had that script :-)

**Comment by coeing** [comment]
I will throw it out :)
