### ISSUE TITLE
Received invalid - State within openhab not updated properly

### ISSUE THREAD

**Issue by Lyann** [stefan-kaestle/openhab2-addons#101]
Receiving a lot invalid types messages:
[hc.internal.services.BoschSHCService] - Received invalid, expected type org.openhab.binding.boschshc.internal.services.temperaturelevel.dto.TemperatureLevelServiceState
[hc.internal.services.BoschSHCService] - Received invalid, expected type org.openhab.binding.boschshc.internal.services.valvetappet.dto.ValveTappetServiceState
[hc.internal.services.BoschSHCService] - Received invalid, expected type org.openhab.binding.boschshc.internal.services.shuttercontact.dto.ShutterContactServiceState
...

Dumping the json which is received by the bosch device reveals a different name: {"@type":"temperatureLevelState","temperature":20.4}. 

When I compare it with the code you see that state is added and does not match the String specification within the object TemperatureLevelServiceState, which is without the postfix.

Results for client: Not updating of any bosch device value within the openhab interface.

Any idea why it occurs suddenly (Home controler version 9.23.1937-18234)?

**Comment by coeing** [comment]
@Lyann Thanks for your report! 

Could you enable debug or trace logging and post the logs around the warning? This should help a lot with finding the bug :)

**Comment by coeing** [comment]
@Lyann No need for the logs as I could reproduce (and fix) it in my own system as well :)
