### ISSUE TITLE
Support for Groundfloor Heating Controller (Fussbodenheizung)

### ISSUE THREAD

**Issue by coeing** [stefan-kaestle/openhab2-addons#103]
See https://github.com/openhab/openhab-addons/issues/10767

**Comment by coeing** [comment]
This might be solved by a new version with the Wall Thermostat in it. I will wait for a comment by the reporter.

**Comment by jensflorian** [comment]
I can confirm, the Wall thermostat can also used to read temperature and humidity from a 230V floor heating controller.

**Comment by david-pace** [comment]
We are moving all issues from this personal repository to the official openhab-addons repository. If I interpret the previous comment correctly, there is at least a workaround that provides partial support. Feel free to open new issues in [the official openhab-addons repository](https://github.com/openhab/openhab-addons/issues) if you need a more specific thing type to support all features.
