### ISSUE TITLE
Version 1.2

### ISSUE THREAD

**Issue by coeing** [stefan-kaestle/openhab2-addons#106]
There are already some important bugfixes (e.g. #66) and some features that would be great to bring to the public (including @MarkJonas ;) ). So I would suggest to open a new release branch, building a new release candidate and open a pull request to merge it into openHAB.

Initially I would have liked to wait for the main feature "Discovery" to be available, but we can easily publish it in the next release.

@GerdZanker @stefan-kaestle What's your opinion about it?

**Comment by GerdZanker** [comment]
>Initially I would have liked to wait for the main feature "Discovery" to be available, 

do not wait

>we can easily publish it in the next release.

another pull request shouldn't take too long.

**Comment by coeing** [comment]
Alright, I merged the latest code from openHAB, created a release branch (releases/v1.2) and built a first release candidate (https://github.com/stefan-kaestle/openhab2-addons/releases/tag/v1.2-rc1). 

Here is a list of issues that were fixed since 1.1:
- #46 
- #40 
- #34 
- #83 
- #84 
- #25 
- #66 
- #41 
- #101 
- #63 

It would especially be great to have some testers for the new things/devices we added. We developers only have a handful devices at home and can not test all scenarios ourselves.

@MarkJonas Hope that version works for you! If not, let us know. I am not sure if we might have to create a release candidate with the code from openHAB 3.1 instead if there were breaking changes in 3.2

**Comment by coeing** [comment]
The plan is to have two weeks of testing. Afterwards I will create a pull request in the official openHAB repository for our new release.

**Comment by MarkJonas** [comment]
> The plan is to have two weeks of testing. Afterwards I will create a pull request in the official openHAB repository for our new release.

I installed the updated binding this morning and it was accepted by openHAB 3.1.0.

What I noticed though is that the *settings/addons/binding* bindings page shows 3.1.0 as the version of the binding.

![image](https://user-images.githubusercontent.com/12135716/127841937-d7dded35-f924-4f82-9c68-df324fcebc6b.png)

But the *bundle:list* command shows 3.2.0:
```
264 │ Active │  80 │ 3.2.0.202107292001    │ org.openhab.binding.boschshc
```

**Comment by MarkJonas** [comment]
The v1.2-rc1 binding is working fine since I installed it 2.5 days ago. :+1: :smile:

**Comment by coeing** [comment]
As the new version seems to work fine so far (I tested #109, but could not reproduce the issue), I will open a pull request in the main openHAB repository now :)

**Comment by coeing** [comment]
Pull Request is still pending: https://github.com/openhab/openhab-addons/pull/11134

**Comment by MarkJonas** [comment]
> Pull Request is still pending: [openhab#11134](https://github.com/openhab/openhab-addons/pull/11134)

Is it maybe because the PR build check is failed and thus the PR is blocked?

![image](https://user-images.githubusercontent.com/12135716/132248774-a0504dc2-7420-4fc1-98f7-070d0ac832d9.png)

When looking into the referenced [build 5426](https://ci.openhab.org/job/PR-openHAB-Addons/5426/) I see that the Bosch Smart Home Binding failed.

![image](https://user-images.githubusercontent.com/12135716/132248878-76076d2b-361f-42d9-8b97-9da522afbef8.png)

Looking at the [build's console output](https://ci.openhab.org/job/PR-openHAB-Addons/5426/org.openhab.addons.bundles$org.openhab.binding.boschshc/console) reveals two warnings which most likely fail the build.

```
...
[WARNING] /home/jenkins/jenkins-agent1/workspace/PR-openHAB-Addons@3/bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/BridgeHandler.java:[326,56] Potential null pointer access: this expression has a '@Nullable' type
...
[INFO] --- bnd-maven-plugin:5.3.0:bnd-process (default) @ org.openhab.binding.boschshc ---
[INFO] Individual report appended to summary report.
[WARNING] Code Analysis Tool has found: 
 0 error(s)! 
 2 warning(s) 
 0 info(s)
[WARNING] org.openhab.binding.boschindego.internal.BoschIndegoHandlerFactory.java:[35]
Classes/Interfaces/Enums should be annotated with @NonNullByDefault
[WARNING] org.openhab.binding.boschindego.internal.handler.BoschIndegoHandler.java:[52]
Classes/Interfaces/Enums should be annotated with @NonNullByDefault
...
```

**Comment by coeing** [comment]
@MarkJonas Thanks for the hint! The warnings are not from our binding though, so we can not fix them :) But I could try to merge the latest changes from the main openHAB branch into our release branch.

**Comment by coeing** [comment]
@MarkJonas It was an error during the static code analysis of our binding. Fixed it now, hopefully the build is successful now :)

**Comment by coeing** [comment]
Build was successful, now we have to wait for the openHAB maintainers: https://ci.openhab.org/job/PR-openHAB-Addons/5432/ 👍

**Comment by coeing** [comment]
Yay, it's merged! :) https://github.com/openhab/openhab-addons/pull/11134
