### ISSUE TITLE
Update version number from 3.1.0 to 3.2.0

### ISSUE THREAD

**Issue by coeing** [stefan-kaestle/openhab2-addons#107]
> The plan is to have two weeks of testing. Afterwards I will create a pull request in the official openHAB repository for our new release.

I installed the updated binding this morning and it was accepted by openHAB 3.1.0.

What I noticed though is that the *settings/addons/binding* bindings page shows 3.1.0 as the version of the binding.

![image](https://user-images.githubusercontent.com/12135716/127841937-d7dded35-f924-4f82-9c68-df324fcebc6b.png)

But the *bundle:list* command shows 3.2.0:
```
264 │ Active │  80 │ 3.2.0.202107292001    │ org.openhab.binding.boschshc
```

_Originally posted by @MarkJonas in https://github.com/stefan-kaestle/openhab2-addons/issues/106#issuecomment-890890754_

**Comment by coeing** [comment]
I did not find any place to update this version number, I guess it is set by openHAB itself? @GerdZanker Do you know if it is possible to set this version number? If not I would like to close this issue.

**Comment by GerdZanker** [comment]
I don't know it. 
I think that the ``bundle:list`` version is the one defined via the "bundles/org.openhab.binding.boschshc/pom.xml" -> parent version. For the other version I guess it could be the ``${project.version}`` in "bundles/org.openhab.binding.boschshc/src/main/feature/feature.xml".

**Comment by coeing** [comment]
@GerdZanker Alright, thanks! For me it looks like the `${project.version}` is set by openHAB during their builds, so it will be fixed there.
