### ISSUE TITLE
Support for Thermostat SilentMode

### ISSUE THREAD

**Issue by jensflorian** [stefan-kaestle/openhab2-addons#110]
The latest firmware update has added another channel to the Bosch Smart Home Thermostat.
In addition to ChildLock it has now support for silent operation of the valve tappet (this however increases battery usage).

Unfortunately there is no updated information available at https://apidocs.bosch-smarthome.com/local/
The new service is located /services/SilentMode/state and can be viewed via postman.
I don't know if its possible to change the values via API:

Default is:
{
    "@type": "silentModeState",
    "mode": "MODE_NORMAL"
}

After changing to silent mode via app it says:

{
    "@type": "silentModeState",
    "mode": "MODE_SILENT"
}

**Comment by david-pace** [comment]
The issue was moved to the official openhab-addons repository: https://github.com/openhab/openhab-addons/issues/14779
