### ISSUE TITLE
Looking for developers!

### ISSUE THREAD

**Issue by coeing** [stefan-kaestle/openhab2-addons#114]
Hey there!

Hope you all have a nice Christmas time in those uncertain times!

Now that a new version of our binding was merged into the openHAB main branch I decided to stop my development in this project. Main reason is that I am not actively using openHAB right now. I am still planning to make my home smarter by setting up a real openHAB solution, but until then it makes no sense for me to help developing a piece of software I am not using myself. It just feels wrong :) 

I hope that there are other devs that may already use our binding who can jump in now to help @GerdZanker and @stefan-kaestle to maintain and further develop the binding. There are still some open issues and Bosch devices that are not supported yet.

Happy holidays everybody
Christian

**Comment by stefan-kaestle** [comment]
Thanks for your help Christian, much appreciated. 

I also wish you and your family a happy Christmas. Take care of yourself!

**Comment by GerdZanker** [comment]
Hello @coeing,

thank you for pushing the opehab binding for Bosch SmartHome forward! I really appreciated your energy and stamina in each and every related pull request.

All the best for Christmas and happy coding,
Gerd

**Comment by GerdZanker** [comment]
One new developer joined: Welcome David!
[Code Owner list is updated](https://github.com/openhab/openhab-addons/pull/14693)
