### ISSUE TITLE
New channel (child lock state) is missing after binding upgrade

### ISSUE THREAD

**Issue by jensflorian** [stefan-kaestle/openhab2-addons#115]
With OpenHab 3.2 the BSH binding introduced the Child-lock state channel to the thermostats.
Unfortunately, the new channels don’t appear in the UI. The new channel will appear on newly-created thermostats.

For a possible solution: See also: https://community.openhab.org/t/adding-new-channels-to-binding/110877

**Comment by david-pace** [comment]
This is a general issue that has to be solved on a more global level in the openHAB infrastructure. If I interpret the linked discussion correctly, this should now work in newer openHAB versions.

We are moving all issues in this personal repository to the official openhab-addons repository. Please report any further issues in https://github.com/openhab/openhab-addons/issues.
