### ISSUE TITLE
Support of Bosch Universal Switch (Flex)

### ISSUE THREAD

**Issue by moritzbeck13** [stefan-kaestle/openhab2-addons#116]
Is the [Bosch Universal Switch (Flex)](https://www.bosch-smarthome.com/de/de/produkte/bedienelemente-und-zubehoer/universalschalter/) currently supported?
The openHAB documentation only mentions in-wall switches and plugs (which additionally also measure power and energy usage). I also couldn't find any other smart home solution that seems to support it.

If not, is it possible to support it? Or is that a limitation of the Bosch SHC API?
Has anyone tried to integrate it with the intrusion detection system? I also cannot seem to find any documentation for that.

**Comment by GerdZanker** [comment]
Hello @moritzbeck01,

currently there is no support for the Universal Switch. This devices is also missing in the list of my own smart home devices. Therefore we need a contribution from the community, beause I can't develop and test it.

But you could give the in-wall switch a try. If the API for the Universal Switch communication is the same as for the in-wall switch it could work.

**Comment by moritzbeck13** [comment]
Hey @GerdZanker, thanks for the answer!

If I decide to buy it I certainly would be willing to give it a try, but are there even any hints in the API of it being supported at all? The latest change to the repo here on GitHub is from January 2021, so I have some concerns regarding that.

I also thought about using the in-wall switch instead, but when I just need a switch to control a virtual device, drilling a hole in the wall seems like too much of a hassle, even though the price difference of those two isn't even that big.
