### ISSUE TITLE
Discover Bosch Home Controller Bridge automatically

### ISSUE THREAD

**Issue by coeing** [stefan-kaestle/openhab2-addons#13]
Would it be possible to discover the IP address automatically? If not we could add a link to the official Bosch support page which describes how to find out the IP: https://www.bosch-smarthome.com/de/de/service/bei-der-erstinstallation-werde-ich-nach-der-ip-adresse-des-shc-gefragt

We could ask in the Bosch GitHub repository (https://github.com/BoschSmartHome/bosch-shc-api-docs) how an automatic discovery could be done. The official Bosch Smart Home app does it as well, so it might be possible: https://tt-smarthome.resource.bosch.com/documents/Manual/UK/System_Solutions/Controller_EN_161109_web.pdf

Feedback from @GerdZanker :
> The SHC returns public information without pairing.
If we assume that both - SHC and OpenHAB - have IPs in the same network it should be possible find with a simple try & error approach.
I suggest to add/implement this later, after this PR, via a SHC bridge discovery service.

**Comment by jensflorian** [comment]
Maybe detection via FDQN identifier, see: https://github.com/hxmelab/node-red-contrib-bosch-shc/commit/1686cc47e17c7ee325fa31d7b3e7ceb3b36980f4 ?

**Comment by GerdZanker** [comment]
See also https://github.com/BoschSmartHome/bosch-shc-api-docs/issues/39

**Comment by GerdZanker** [comment]
Replaced with [openhab-addons#14195](https://github.com/openhab/openhab-addons/issues/14195)
