### ISSUE TITLE
Refactor code to follow official openHAB guidelines

### ISSUE THREAD

**Issue by coeing** [stefan-kaestle/openhab2-addons#16]
The guidelines are here: https://www.openhab.org/docs/developer/guidelines.html

We should follow them as closely as possible.

Here are some first TODOs:

- [x] Add correct Null Annotations (https://www.openhab.org/docs/developer/guidelines.html#null-annotations)
- [x] Check logger usages (https://www.openhab.org/docs/developer/guidelines.html#f-logging)
- [x] Add documentation for all classes & methods (https://www.openhab.org/docs/developer/guidelines.html#c-documentation)
- [x] Run Spotless Maven Plugin to format code (https://www.openhab.org/docs/developer/guidelines.html#code-format)
- [x] Format XML files correctly (https://www.openhab.org/docs/developer/guidelines.html#xml-files)
- [x] Every Java file must have a license header. You can run mvn license:format on the root of the repo to automatically add missing headers.

**Comment by coeing** [comment]
Based on the feedback from Hilbrand (https://community.openhab.org/t/towards-merging-the-new-bosch-shc-binding/101952/2) we should cleanup our code to follow the official guidelines before we create our pull request.

Feel free to add more TODOs. We can also split the task into more issues, it might be a bit of work.

**Comment by stefan-kaestle** [comment]
Biggest issue might be signing off code. We have to rebase and change the commit messages and the force push. 

That's going to be nasty with merges. We already have two, so no idea how to best do this. Maybe git filters are the way to go. https://stackoverflow.com/questions/13043357/git-sign-off-previous-commits

In any case, we need to synchronize here, so that we don't mess up each others work. Maybe we merge the remaining open PRs first? We already have merges, so having a few more shouldn't make the problem worse? :-P

**Comment by coeing** [comment]
@stefan-kaestle Yes, it might take some work to go through the commits again. I will do it for my pull request branch and maybe @GerdZanker can do it for his as well? If you have time for it, you can adjust the bosch-shc-2.5 branch. If not, let me know, than I can do it :)

The easiest way is to recommit all the commits and adjust the commit message. The push has to be "forced" because changing the commit messages changes the git history. We don't have to merge the pull requests first. It is a widespread practice to rebase pull request branches anyway before a merge, and we can adjust the commit messages during the rebase as well.

**Comment by coeing** [comment]
Just rebased my pull requests and force-pushed it, there doesn't seem to be any problem with it 👍 https://github.com/stefan-kaestle/openhab2-addons/pull/15

**Comment by coeing** [comment]
@stefan-kaestle Played around with the bosch-shc-2.5 branch a bit and it shouldn't be a problem there as well. We just should make sure to keep the merge commits so we don't loose the pull request branches (I like that they group the commits that belong to a feature). Other than that it only changes the commit name and email to the one who does the rebase, but the authors of the commits stay the same.

A question that came to my mind: We should probably always use the author of the commit behind the "Signed off by", shouldn't we? On the other hand it might not be correct to sign off a commit for another person. Not sure about it, it's the first time I hear about this sign-off thing :) In this thread it sounds like another person can sign off commits of other authors. In that case the sign-off person have the word of the original author that they have the copyright for the committed code: https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for

I use TortoiseGit as my Git UI, but here are the steps for the sign-off with rebase with vanilla Git: https://stackoverflow.com/questions/25570947/how-to-use-git-interactive-rebase-for-signing-off-a-series-of-commits

**Comment by coeing** [comment]
Checked correct usage of null annotations and added a pull request for it :)

**Comment by coeing** [comment]
The code format check `mvn spotless:check -Dspotless.check.skip=false` gives me:
```
[INFO] Scanning for projects...
[WARNING] The POM for org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for org.eclipse.m2e:lifecycle-mapping:1.0.0: Plugin org.eclipse.m2e:lifecycle-mapping:1.0.0 or one of its dependencies could not be resolved: Failure to find org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 in https://jcenter.bintray.com was cached in the local repository, resolution will not be reattempted until the update interval of jcenter 
has elapsed or updates are forced
[INFO]
[INFO] ------< org.openhab.addons.bundles:org.openhab.binding.boschshc >-------
[INFO] Building openHAB Add-ons :: Bundles :: BoschSHC Binding 2.5.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for org.eclipse.m2e:lifecycle-mapping:1.0.0: Plugin org.eclipse.m2e:lifecycle-mapping:1.0.0 or one of its dependencies could not be resolved: Failure to find org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 in https://jcenter.bintray.com was cached in the local repository, resolution will not be reattempted until the update interval of jcenter 
has elapsed or updates are forced
[INFO]
[INFO] --- spotless-maven-plugin:1.24.3:check (default-cli) @ org.openhab.binding.boschshc ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.736 s
[INFO] Finished at: 2020-07-12T01:01:00+02:00
[INFO] ------------------------------------------------------------------------
```
So this seems to be okay.

**Comment by GerdZanker** [comment]
I'm back from a longer offline periode, starting with a rebase/recommit of the PR #11 including the sign-off.

Regarding
> We should probably always use the author of the commit behind the "Signed off by", shouldn't we? 

Yes, I think this is best way to avoid questions and confusions and additional work for us to proove to have the contribution right.

**Comment by GerdZanker** [comment]
Found one more todo in [guidelines directory-and-file-layout](https://www.openhab.org/docs/developer/guidelines.html#a-directory-and-file-layout):

- [ ] Every Java file must have a license header. You can run ``mvn license:format`` on the root of the repo to automatically add missing headers.

**Comment by GerdZanker** [comment]
Class documentation is now merged with #21

**Comment by GerdZanker** [comment]
I reviewed the guide lines
>JavaDoc is required to describe the purpose and usage of every:
>1. class,
>1. interface,
>1. enumeration (except inner classes and enums),
>1. constant, field and method with visibility of default, protected or public.

I think we covered the first three quite well, but I have no idea about regarding public & protected constant, field and method JavaDoc. Shall we just await the view of the OpenHAB maintainers?

**Comment by coeing** [comment]
@GerdZanker I would like to close this issue for now, it has already become too long (always happens with general issues). But I'll look for uncommented constants, fields and methods while working on other issues :) The remaining misses should be found during the openHAB review.
