### ISSUE TITLE
Pre-Release for external testers

### ISSUE THREAD

**Issue by coeing** [stefan-kaestle/openhab2-addons#19]
As we are working on the first release it might be a good time to invite some external testers to check out our binding so we might get some reports for bugs we haven't found yet.

One interested person already ask to test it: https://community.openhab.org/t/will-there-be-a-bosch-smart-home-binding/8910/81

Could we add a binary as a GitHub release in this repository? I don't see the tab here yet, but maybe it just has to be activated in the settings by the repository owner @stefan-kaestle ? :) I remember that the issue tracker was also off by default.

**Comment by coeing** [comment]
As soon as it's possible to create a release I can build one locally for external people to test.

**Comment by kreack** [comment]
Hey guys ;-) 
I'm happy to support you by test activities... 

Regards, Sergo

**Comment by tuxianerDE** [comment]
Folks, I would join that offer to test a pre-release. I am planning to use Openhab mainly readonly with my Bosch System - yet. But I am happy to support the community as I love the stuff Bosch offers but same goes for the control I have over Openhab.

**Comment by coeing** [comment]
@stefan-kaestle You are probably busy with other projects. If you find some minutes could you enable the Releases feature for this repository? Than I can upload a binary as a pre-release for our external testers :)

**Comment by coeing** [comment]
@stefan-kaestle Forget about it, just found out that it is already enabled :) https://github.com/stefan-kaestle/openhab2-addons/releases/new
I will create a pre-release version soon from our main branch.

**Comment by Dfinity-skaestle** [comment]
> @stefan-kaestle Forget about it, just found out that it is already enabled :) https://github.com/stefan-kaestle/openhab2-addons/releases/new
> I will create a pre-release version soon from our main branch.

Sorry, yes, quite busy. But will enable that feature and see if I can give the two of you admin privileges.

**Comment by Dfinity-skaestle** [comment]
> @stefan-kaestle You are probably busy with other projects. If you find some minutes could you enable the Releases feature for this repository? Than I can upload a binary as a pre-release for our external testers :)

Yes, sorry, a bit busy these days.
I love how the two of you take such good care of the project! Thank you so much!

**Comment by stefan-kaestle** [comment]
> @stefan-kaestle You are probably busy with other projects. If you find some minutes could you enable the Releases feature for this repository? Than I can upload a binary as a pre-release for our external testers :)

Sorry, quite busy, yes. I love how the two of you take such good care of the project,  thought. Thank you! 💕

**Comment by coeing** [comment]
@kreack @tuxianerDE Sorry for the delay, I didn't see that creating new releases was already possible :/ But here you go! https://github.com/stefan-kaestle/openhab2-addons/releases/tag/0.1

Please create new issues while testing, so we get immediate feedback. Bug reports (even for minor bugs) are most important of course, but you could also create issues about:
- Information that is missing or not easily understandable (especially to setup the addon!) => We will enhance our README.md and the information on screen
- Enhancements for existing bindings you like to see in later versions
- New bindings you like to see

Don't be afraid to create an issue that only contains basic information. You can easily add missing information later and we will ask for specific information when we need it :)

Thanks for your time!
