### ISSUE TITLE
OFFLINE COMMUNICATION_ERROR - Bosch Window/Door Contact

### ISSUE THREAD

**Issue by kreack** [stefan-kaestle/openhab2-addons#23]
Hi guys, 

after paring of BSH Controller, i tried to add the window/door contacts. I get the following error message: OFFLINE COMMUNICATION_ERROR
<img width="815" alt="image" src="https://user-images.githubusercontent.com/62901914/89720691-4a896080-d9d5-11ea-83d2-06b22882446b.png">
<img width="765" alt="image" src="https://user-images.githubusercontent.com/62901914/89720711-8cb2a200-d9d5-11ea-9e46-b825bde46546.png">

**Item definition:** 
Contact Sensor_Eingangstuer_Status  "Sensor Eingangstür"    <frontdoor>    (Flur)           {channel="boschshc:window-contact:851459af:contact"}

**Log (despite error message):**
2020-08-09 00:23:25.778 [INFO ] [chshc.internal.BoschSHCBridgeHandler] - Got update for hdm:HomeMaticIP:3014F711A000009A18592258
2020-08-09 00:23:25.779 [WARN ] [chshc.internal.BoschSHCBridgeHandler] - longPoll: child handler for null does not implement Bosch SHC handler

**Result:** 
no status is transferred

Do you have any idea how to fix this? 
Thanks in advance.

**Comment by tuxianerDE** [comment]
Hi, that channel definition looks strange to me... boschshc:window-contact:851459af:contact

I got them all working..  can you share your complete thing configuratio?

**Comment by kreack** [comment]
Hi @tuxianerDE,

configuration was marked directly in paper ui. The fully configuration of things looks like: 
<img width="765" alt="image" src="https://user-images.githubusercontent.com/62901914/89729824-7d654000-da39-11ea-9454-a541534f3dcd.png">

The detail thing configuration for thermostat is (and looks fine / need to be tested in detail): 
<img width="765" alt="image" src="https://user-images.githubusercontent.com/62901914/89729845-bbfafa80-da39-11ea-96ea-cdc094084c3c.png">

The configuration for sensors looks like: 
<img width="765" alt="image" src="https://user-images.githubusercontent.com/62901914/89729884-23b14580-da3a-11ea-9b72-49df9ba942ef.png">
after adding of detail Item configuration the connection status go to error...

**Comment by kreack** [comment]
@tuxianerDE can you share your configuration of the bush things?

**Comment by tuxianerDE** [comment]
I do everything in the config files but here you go:

   Thing window-contact wohnzimmerfensterlinks "Wohnzimmer Fenster" @ "Wohnzimmer" [ id="hdm:HomeMaticIP:3014F711AXXXXXXXXX" ]

Here the item:
Contact WohnzimmerlinksFensterKontakt "Fenster Kontakt Wohnzimmer Links" (persSwitch) { channel="boschshc:window-contact:holzgasse:wohnzimmerfensterlinks:contact"}

**Comment by kreack** [comment]
after change of configuration from paper ui to file its looks more better :-) 
thanks @tuxianerDE
