### ISSUE TITLE
run.sh still required?

### ISSUE THREAD

**Issue by coeing** [stefan-kaestle/openhab2-addons#29]
I just stumbled upon the "run.sh" file in the root folder of our bundle. Is that script still required? If not we should throw it out :)

**Comment by coeing** [comment]
Furthermore the "install.sh" script seems to have only local paths. We should either not have it under version control or make the paths configurable, so it can be used by all developers.

**Comment by GerdZanker** [comment]
> Furthermore the "install.sh" script seems to have only local paths.

I used the script to get some infos and ideas for my own steps to compile and test the JAR.
My recommendation is to remove the script and write instead some word for developers into the readme. What do you think?

**Comment by coeing** [comment]
@GerdZanker Sounds good, we can add a Developers section to the README.md. Feel free to use the already existing pull request #31 to adjust the file :)

**Comment by GerdZanker** [comment]
>Feel free to use the already existing pull request #31 to adjust the file :)

Perfect! But I can't promise a time frame for the dev section, therefore merge at any point in time and depending on the state I will reuse your PR or create a new one.

**Comment by coeing** [comment]
@GerdZanker In that case I'll merge it now and you can adjust the README.md when you have time :)
