### ISSUE TITLE
Support for Thermostats

### ISSUE THREAD

**Issue by coeing** [stefan-kaestle/openhab2-addons#3]
As I have two at home, I'd like to add a handler for them to the binding.

The Bosch API can be found here:
https://apidocs.bosch-smarthome.com/local/index.html (Select a definition: Thermostat)

As the official API doesn't have endpoints to change the state of the device, the first version of the handler will contain:
- Providing the temperature measured at the device
- Providing the valve tappet position of the device

I will also open an issue in the official Bosch API repository https://github.com/BoschSmartHome/bosch-shc-api-docs to ask for the current state of the Thermostat API. Maybe there are more functions which are not documented yet or they are coming soon. As the devices can be controlled by other apps, chances are that they have all the functionality already.

**Comment by coeing** [comment]
@stefan-kaestle If you like you can set me as the Assignee already, I will start with the issue soon :)

**Comment by stefan-kaestle** [comment]
Much appreciated, happy to have you helping with the binding :-)

**Comment by coeing** [comment]
Right now I am adding the valve tappet position channel to the thermostat. I also created an issue about the possibility to set the desired temperature at a thermostat via the API: https://github.com/BoschSmartHome/bosch-shc-api-docs/issues/35

TODOS:
- [ ] Valve Tappet Position channel
- [ ] Handle processUpdate method in a generic way be registering services on initialization of a handler

**Comment by coeing** [comment]
Just received an answer about setting the desired temperature for a room. It is controlled via virtual RoomClimateControl devices (https://github.com/BoschSmartHome/bosch-shc-api-docs/issues/35).

I will add a separate handler for those although they are no real things. But they are indeed separate from specific thermostats because you can have one RoomClimateControl controlling multiple thermostats in a room.

**Comment by coeing** [comment]
Pull request is merged, the new Thermostat binding is available :)
