### ISSUE TITLE
POM error during Travis build

### ISSUE THREAD

**Issue by coeing** [stefan-kaestle/openhab2-addons#44]
https://travis-ci.com/github/openhab/openhab-addons/jobs/379252414

@GerdZanker Maybe you can have a look at this? You seemed to be the most experienced of us for that file :) You can probably ask for help in the pull request if you don't see the issue immediately.

**Comment by coeing** [comment]
Fixed by rebasing onto current openHAB 2.5.x branch and increasing version number of bundle to 2.5.9-SNAPSHOT in pom.xml

**Comment by GerdZanker** [comment]
Hello @coeing, wow, what a great work from you! Thanks a lot!
Looks like you had a rainy weekend and nothing else to do... ;) and I'm now a too late to support with the major topics.

**Comment by coeing** [comment]
@GerdZanker No, the weekend was busy enough, but I just wanted to kick off the pull request to get to the first release :)
