### ISSUE TITLE
Readme.md - Outdated paragraph "Binding Configuration"

### ISSUE THREAD

**Issue by coeing** [stefan-kaestle/openhab2-addons#5]
From the Readme.md:
> Bosch IDs for devices are displayed in the OpenHab log on bootup.

```
Bridge boschshc:shc:1 [ ipAddress="192.168.x.y" ] {
  Thing in-wall-switch bathroom "Bathroom" [ id="hdm:HomeMaticIP:3014F711A000XXXXXXXXXXXX" ]
  Thing in-wall-switch bedroom "Bedroom" [ id="hdm:HomeMaticIP:3014F711A000XXXXXXXXXXXX" ]
  Thing in-wall-switch kitchen "Kitchen" [ id="hdm:HomeMaticIP:3014F711A000XXXXXXXXXXXX" ]
  Thing in-wall-switch corridor "Corridor" [ id="hdm:HomeMaticIP:3014F711A000XXXXXXXXXXXX" ]
  Thing in-wall-switch livingroom "Living Room" [ id="hdm:HomeMaticIP:3014F711A000XXXXXXXXXXXX" ]

  Thing in-wall-switch coffeemachine "Coffee Machine" [ id="hdm:HomeMaticIP:3014F711A0000XXXXXXXXXXXX" ]

  Thing twinguard      tg-corridor    "Twinguard Smoke Detector" [ id="hdm:ZigBee:000d6f000XXXXXXX" ]
  Thing window-contact window-kitchen "Window Kitchen"           [ id="hdm:HomeMaticIP:3014F711A00000XXXXXXXXXX" ]
  Thing window-contact entrance       "Entrance door"            [ id="hdm:HomeMaticIP:3014F711A00000XXXXXXXXXX" ]

  Thing motion-detector  motion-corridor "Bewegungsmelder"      [ id="hdm:ZigBee:000d6f000XXXXXXX" ]
}
```

Not sure about this, but in my openHAB log the logs look like this:
```
2020-06-15 18:18:39.788 [WARN ] [chshc.internal.BoschSHCBridgeHandler] - Found device: name=Rollladen id=hdm:HomeMaticIP:3014F711A00018D6D859A52C
2020-06-15 18:18:39.790 [WARN ] [chshc.internal.BoschSHCBridgeHandler] - Found device: name=-RoomClimateControl- id=roomClimateControl_hz_6
2020-06-15 18:18:39.791 [WARN ] [chshc.internal.BoschSHCBridgeHandler] - Found device: name=Rollladen id=hdm:HomeMaticIP:3014F711A00018D6D859A3C4
2020-06-15 18:18:39.792 [WARN ] [chshc.internal.BoschSHCBridgeHandler] - Found device: name=Central Heating id=hdm:ICom:819410185
```

**Comment by coeing** [comment]
In any case the log file in which to find the logs should be written down, there are multiple (probably it's the main log at `${OPENHAB_CONF}/openhab.log`?)

**Comment by GerdZanker** [comment]
My small input
- it was confusing to read about "Binding Configuration" but need to enter the content into a ``*.things`` file.
- same for the "Thing configuration" which has to go into a ``*.items`` file

and it would be great if the openHAB log output could be copied & pasted into the ``*.things`` file, but currently the name and the ID are not surrounded by "".

**Comment by stefan-kaestle** [comment]
I guess eventually, this should be done by the auto discovery. People will struggle if they need to dig in the logs :-)

**Comment by meyouandi** [comment]
Hi,
I tried it out. Following this thread it was even for me (novice) possible to use the ID's from the logs to add my things.
Thanks for your work. Of course auto discovery would be great and would ease the use.
Thanks for your great work!

**Comment by coeing** [comment]
Alright, to close this issue I will update the Readme.md to reflect the current way to add devices by looking into the openHAB log. For the auto discovery feature I added a new issue #27 We can implement that feature after the first release.
