### ISSUE TITLE
Please support the smoke detector for fire detection and siren

### ISSUE THREAD

**Issue by VL2019** [stefan-kaestle/openhab2-addons#51]
It would be nice to get the Information (event) if the smoke detector detect a fire. This information could be important for existing devices in OpenHAB like open the shutters or push notifications to the mobile phone or external gong in the garden.

In addition to that I wish a switch to start the alarm siren. For example if a burglar enters the house, I would like to start the siren. 

Device: https://www.bosch-smarthome.com/uk/en/shop?url=products/smart-system-solutions/smoke-detector

**Comment by coeing** [comment]
The SmokeDetector service is also required for the Twinguard device, so we could enhance the Twinguard thing and add a new SmokeDetector thing with one service.

**Comment by coeing** [comment]
Smoke Detector is documented in the API docs: https://apidocs.bosch-smarthome.com/local

**Comment by GerdZanker** [comment]
Smoke detector devices are now supported, see related [OpenHub Issue](https://github.com/openhab/openhab-addons/issues/13759).

The other enhancement are pending.
