### ISSUE TITLE
Handle change of Home Controller system password correctly

### ISSUE THREAD

**Issue by coeing** [stefan-kaestle/openhab2-addons#55]
A change of SHC "system password" is an issue and happening also during initial setup of the binding e.g. if the wrong password was used instead of the App password.

See also [comments](https://community.openhab.org/t/will-there-be-a-bosch-smart-home-binding/8910/102?u=gerdzanker) in openhabCommunity.

The current solution is to **delete the <userdata>/etc/oss_openhab_binding_*.jks file in your openhab installation** because the binding will recreate the jks file.

TODO from ``BoschSslUtil.java``:
```
                // TODO if SHC system password is changed the keystore can't be loaded and an IOException "... password
                // was incorrect" is thrown
                // Either use a different secret instead of the system password (e.g. openHAB UUID?)
                // or recreate a new keystore with the different system password again (needs pairing)
```

----

In the meantime the [initial pull request](https://github.com/openhab/openhab-addons/pull/8629) is discussed and from comments we can use "reference" code from openhab core how certificate handling is done there. 
See [CertificateGenerator.java](https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.io.jetty.certificate/src/main/java/org/openhab/io/jetty/certificate/internal/CertificateGenerator.java) and the [generateCertificate()](https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.io.jetty.certificate/src/main/java/org/openhab/io/jetty/certificate/internal/CertificateGenerator.java#L157) function how the password, and self singed cert creation is done.

With this reference we should get rid of password problems, by **using a single fixed password ins the code** and **avoid at least the ``bcprov-jdk15on`` bundle dependency**, which increases the jar size a lot.

**Comment by coeing** [comment]
@GerdZanker I think this is fixed with your last pull request, isn't it?

**Comment by GerdZanker** [comment]
Yes, its avoided with PR #70, because the keystore password is now a static password defined in code.
The BoschSHC systempassword is only used for pairing.

Drawback: A new keystore will be created using your SHC IP address and a new pairing is needed.
