### ISSUE TITLE
Window Contact does not show its status

### ISSUE THREAD

**Issue by coeing** [stefan-kaestle/openhab2-addons#56]
@coeing Thanks! Of corse we are still interested :)

I deleted the old Beta1-.jar file (this worked fine) and insert the new beta2 file in openhab folder and reboot the complete System (RP3 with OH 2.5.9 - hope this is compatible with your 3.0 binding). I do not created a new key (pushed NOT the button on the BSH gateway again)

I got this WARN Message in the log file:
`[WARN ] [org.apache.felix.fileinstall        ] - Error while starting bundle: file:/usr/share/openhab2/addons/org.openhab.binding.boschshc-3.0.0-SNAPSHOT.jar `

I noticed an issue with the window-contact. In the log I can see when the status change, but in the "control" view (<IP>/paperui/index.html#/control) there is no status for all window-contacts. I don't know why.

here is my config:

things
```
Bridge boschshc:shc:1 [ ipAddress=„x.xx.x, password=„xxxxx ] {

Thing motion-detector  motion-corridor "Bewegungsmelder"      [ id="hdm:ZigBee:xxxxxxxxx“ ]

Thing twinguard tg-Wohnzimmer  "Twinguard Smoke Detector" [ id="hdm:ZigBee:xxxxxxx“ ]

Thing window-contact BSHtuer "BSH Tuer" [ id="hdm:HomeMaticIP:xxxxxxxxxxx“ ]

Thing window-contact BSHWZrechts "BSH Wohnzimmer rechts" [ id="hdm:HomeMaticIP:xxxxxxxxx7" ]

}
```

items:
```
Number TemperaturWZ "Temperatur Wohnzimmer" (gTemp){ channel="boschshc:twinguard:1:tg-Wohnzimmer:temperature" }

Contact BSHtuer "BSH Haustuer" {channel="boschshc:window-contact:1:BSHtuer:contact"}

Contact BSHWZrechts "BSH Wohnzimmertuer rechts" {channel="boschshc:window-contact:1:BSHWZrechts:contact"}
```

EDIT: I also found an issue with my time. Can not remember if it works fine with the old version. My motion sensor has not the same time like Openhab. There is a difference of exactly two hours. This could also be an issue because of the timezone plus summer/winter time.

`2020-10-21 22:54:29.430 [vent.ItemStateChangedEvent] - Bewegungsmelder_LatestMotion changed from 2020-10-21T19:40:22.638+0000 to 2020-10-21T20:54:29.320+0000`

_Originally posted by @VL2019 in https://github.com/stefan-kaestle/openhab2-addons/issues/14#issuecomment-713868891_

**Comment by coeing** [comment]
@VL2019 Created a new ticket for your issue. I'm not sure if the openHAB 3 bindings work with openHAB 2.5.9. But I can check if the window contact does show up correctly for me as I also have one window contact installed. Will let you know after I tested it!

**Comment by tuxianerDE** [comment]
just tested this with beta 4 and can confirm that I am not getting the proper state and gets updated accordingly. Issue in my view closed.

**Comment by coeing** [comment]
Closing this as we do not support openHAB 2.5.9 but only openHAB 3 and up right now.
