### ISSUE TITLE
Bosch Smart Home Controller Vs Easy Control Smart Thermostat

### ISSUE THREAD

**Issue by JMillwood-92** [stefan-kaestle/openhab2-addons#57]
Hi, I've been checking in with your binding for a little while now and have been very excited to try it out. 

I'm not sure if this is a question or a feature request really.

Essentially I have the Bosch Easy Control Smart Thermostat that seems to do the job of the Smart Home Controller. I think this as I have the Easy Control Smart Thermostat and several Radiator Valves that connect through this thermostat, which is connected to my network and is pingable.

I can connect to the EasyConnect via IFTTT, but would really prefer to access it through OpenHab.

I've installed your latest OpenHab 2 binding but it asks for me to press the pairing button which I don't have.

Is the Smart Thermostat supported by your binding?

Would be happy to try and fix this myself although I'm completely new to the world of Binding development so am not sure where to start.

**Comment by GerdZanker** [comment]
Hallo @JMillwood-92 ,
the Smart Thermostat is not supported by this binding. This binding is for the "Bosch SmartHomeController". I assume the two products are independent and can't be connected together.
But I know that some radiator and room thermostats can be connected to the Bosch SHC, compare with the products page of https://www.bosch-smarthome.com/.

**Comment by stefanoferrario** [comment]
> Hi, I've been checking in with your binding for a little while now and have been very excited to try it out.
> 
> I'm not sure if this is a question or a feature request really.
> 
> Essentially I have the Bosch Easy Control Smart Thermostat that seems to do the job of the Smart Home Controller. I think this as I have the Easy Control Smart Thermostat and several Radiator Valves that connect through this thermostat, which is connected to my network and is pingable.
> 
> I can connect to the EasyConnect via IFTTT, but would really prefer to access it through OpenHab.
> 
> I've installed your latest OpenHab 2 binding but it asks for me to press the pairing button which I don't have.
> 
> Is the Smart Thermostat supported by your binding?
> 
> Would be happy to try and fix this myself although I'm completely new to the world of Binding development so am not sure where to start.

I have the same problem... I have no Bosch SHC but only a Thermostat Buderus TC100 (is the same of Smart Thermostat of Bosch) and some Bosch Valve. Did you find a solution to connect all this to OpenHab?

**Comment by coeing** [comment]
As our binding could not help with this issue, I close it for now.
