### ISSUE TITLE
Add support for Home Connect dryers

### ISSUE THREAD

**Issue by MarkJonas** [stefan-kaestle/openhab2-addons#65]
It would be great if Home Connect dryers like the BOSCH-WTYH7701 would be supported.

```
2021-01-01 10:31:53.026 [INFO ] [devices.bridge.BoschSHCBridgeHandler] - Found device: name=Trockner id=hdm:homeconnect:BOSCH-WTYH7701-68A40EXXXXXX
```

**Comment by Digitalvitamin** [comment]
@MarkJonas: Have a look at the HomeConnect addon (in development: https://community.openhab.org/t/home-connect-addon-looking-for-beta-testers/49702/719). HomeConnect devices are not part of the Bosch Smart Home local API (https://apidocs.bosch-smarthome.com/local/).

**Comment by MarkJonas** [comment]
@Digitalvitamin Thanks for the hint. I assumed that it was the same API because the dryer is also accesible via the Bosch Smart Home App.

@coeing I propose to close this issue as requested improvement is out of scope of this binding. https://github.com/bruestel/org.openhab.binding.homeconnect seem to be the right binding.
