### ISSUE TITLE
Use without bridge but only with Thermostat and some Valves

### ISSUE THREAD

**Issue by stefanoferrario** [stefan-kaestle/openhab2-addons#67]
Hi,

I need to connect to openHAB my Thermostat and some Bosch Valves. The Thermostat is connected to home wlan and has an IP address.
There is a possibility to use it without the bridge?

Thanks a lot

**Comment by coeing** [comment]
Hi @stefanoferrario,

Sorry, but that's not possible with our binding. We communicate with the Bosch Home Controller (the bridge) only and not directly with the devices.
