### ISSUE TITLE
Put each device in an own subfolder

### ISSUE THREAD

**Issue by coeing** [stefan-kaestle/openhab2-addons#7]
I already did it for the Shutter Control (shuttercontrol) and I think it would make the bundle cleaner now and when new devices arrive. I would do the refactoring but would like to hear your feedback first! :) Maybe there could be even a common parent folder "devices" to separate them from other areas, but that could also be another step later if we see that it's necessary.

**Comment by coeing** [comment]
This could go hand in hand with migrating the old handlers to the new service architecture (see #8).

**Comment by coeing** [comment]
@GerdZanker Just moved files and adjusted package names. We should refactor the old handlers to use the new possibilities of the base handler class, but that can happen in separate issues (and probably after the first release).

**Comment by GerdZanker** [comment]
Thank you for your package adjustment. I think the folder structure is easy to understand for reviewers.
The new possibilities can wait after the release and perhaps a new contributor wants to join and start with first work like the base handler class to old handlers. Do we have already an issue for this?

**Comment by coeing** [comment]
@GerdZanker Sounds good 👍 We don't have an issue yet, I will quickly create one.
