### ISSUE TITLE
Change title of binding to "Bosch Smart Home" instead of BoschSHC

### ISSUE THREAD

**Issue by coeing** [stefan-kaestle/openhab2-addons#77]
Right now it is called (at least for my version openHAB 3.1-SNAPSHOT): "BoschSHC Binding"

![image](https://user-images.githubusercontent.com/1310662/106192200-25b7be00-61ac-11eb-92c0-4d1a5387fc88.png)

This is too technical and we should rename it to "Bosch Smart Home".

**Comment by GerdZanker** [comment]
Please let us include this change into our bugfix Version 1.1 because I agree that most openhab users will not know what "SHC" is.
