### ISSUE TITLE
Migrate to API 2.1

### ISSUE THREAD

**Issue by sebastianharder** [stefan-kaestle/openhab2-addons#78]
Support for API 1.0 is dropped, see BoschSmartHome/bosch-shc-api-docs#46

Migration to 2.1 is required.

**Comment by GerdZanker** [comment]
Thanks a lot for this vital information @sebastianharder.

**Comment by coeing** [comment]
@sebastianharder Is the official API documentation at https://apidocs.bosch-smarthome.com/local/ already up-to-date? I/We use that page a lot to get the data structures right :)

**Comment by GerdZanker** [comment]
[Here is the diff](https://github.com/BoschSmartHome/bosch-shc-api-docs/compare/0.5...2.1.0) between the two available releases 0.5 and 2.1. An API Version 1.0 is not tagged in github.

**Comment by coeing** [comment]
@GerdZanker Thanks :) It does not look too different, so we should be fine.

**Comment by coeing** [comment]
@GerdZanker Thanks :) It does not look too different, so we should be fine.

**Comment by sebastianharder** [comment]
@coeing https://apidocs.bosch-smarthome.com/local/ is not yet up-to-date. We are working on it.

For now, everything should still work if you replace the version in the "api-version" header with "2.1".
The version jump from 1.x to 2.x was only due to internal APIs that are not part of the public API. 

However, you might want to consider to support the profiles for the intrusion detection system, which are only available in 2.1.

**Comment by coeing** [comment]
@sebastianharder Thanks for the clarification. About the intrusion detection: We will support more devices over time, let's see what we get into v2 :) We will first support the devices we have at home ourselves, I have no intrusion detection system myself, so it is hard to test the correct implementation.

**Comment by GerdZanker** [comment]
This should be an easy change, because ther is one central ``createRequest`` function.

**Comment by sebastianharder** [comment]
@coeing  https://apidocs.bosch-smarthome.com/local/ is now up-to-date.

Cheers!

**Comment by coeing** [comment]
> @coeing https://apidocs.bosch-smarthome.com/local/ is now up-to-date.
> 
> Cheers!

Thanks @sebastianharder ! That site is my favorite one for information about your API, so it's nice that it is up-to-date :)
