### ISSUE TITLE
Make "main" the main branch

### ISSUE THREAD

**Issue by coeing** [stefan-kaestle/openhab2-addons#82]
Right now it is "master". We are working already on "main" as the main branch.

**Comment by coeing** [comment]
@stefan-kaestle: You are the only one who has the rights to change it, that's why I assign this issue to you :) Feel free to give me and/or @GerdZanker the rights to manage this repository if you feel like it, so we can do such changes in the future.

**Comment by stefan-kaestle** [comment]
Weird. I have you both down. As collaborators since the beginning. I haven't found any more permissions I could assign you.

I will try to make main the main branch.

**Comment by stefan-kaestle** [comment]
Can't do it because it already exists.. going to have a more detailed look tomorrow. It's hard on the phone :->

**Comment by stefan-kaestle** [comment]
Done. Please let me know in case I made a mistake :-)
