### ISSUE TITLE
how-to: install Bosch SHC binding on openHAB2 (2.5.12)

### ISSUE THREAD

**Issue by DirkSander** [stefan-kaestle/openhab2-addons#87]
Hi there!
I updated openHAB2 up to 2.5.12. Unfortunately “Bosch SHC” is not provided as an installable binding. Do I have to build the jar-file on my own from the sources in this repository?

Thanks for your help and your work on the Bosch SHC binding!

Best,
Dirk

**Comment by coeing** [comment]
Hi @DirkSander!

Yes, you can try to build it from the sources, but officially we do not support openHAB2. The development for our first version ended after openHAB3 was already ready for release, so we decided to support openHAB3 only and have no plans to support openHAB 2 as well. But feel free to report back if it worked with your self-build jar, there might be more developers who still use openHAB 2 :) We might as well upload your build jar for other users to use, if you like.

Cheers
Christian

**Comment by coeing** [comment]
Closing this as there are no further questions. @DirkSander If you have more questions feel free to re-open this issue :)
