### ISSUE TITLE
Jar File For Windows

### ISSUE THREAD

**Issue by Powerpitte** [stefan-kaestle/openhab2-addons#91]
Hi,
I run an OpenHab 3 on Windows and I downloaded "org.openhab.binding.boschshc-3.1.0-SNAPSHOT.jar" for testing of my Bosch Twinguard deployment. Do I have to build each version to are jar-file on my own, or can I download that file somehow?
I'm no Software developer, but I have much interested in that topic in special for the Bosch SHC stuff and I would like to help developing.

Best regards
Daniel

**Comment by coeing** [comment]
Hi Daniel,

Thanks for your interest in our binding :) 

In openHAB 3.1.0 you can install our binding directly via the openHAB UI as we are an official addon for openHAB. You can also download the newest version here: https://github.com/stefan-kaestle/openhab2-addons/releases/tag/v1.1-rc1 It is almost the same version without some of the code refactoring we did for the merge into openHAB.

If you have problems running it, feel free to ask!

**Comment by GerdZanker** [comment]
Hello @Powerpitte, every contribution is welcome. As a user you can make suggestions for improvements or supporting the documentation to start slowly into the world of git version control and coding without bothering too much with Java.

**Comment by coeing** [comment]
Closing this as there are no further questions. @Powerpitte Feel free to re-open if your question was not answered correctly :)
