### ISSUE TITLE
Status of devices frozen

### ISSUE THREAD

**Issue by endsideX** [stefan-kaestle/openhab2-addons#98]
I would like to thank you for the great addon. The addon was working good for a few days, but the status of my devices are frozen. All devices are “online”. The following debug log is provided when I open the window:

`21:59:39.441 [DEBUG] [c.internal.devices.bridge.LongPolling] - Sending long poll request
21:59:49.793 [DEBUG] [c.internal.devices.bridge.LongPolling] - Long poll response: {"result":[{"path":"/devices/hdm:HomeMaticIP:3014F711A000009BB85DE504/services/ShutterContact","@type":"DeviceServiceData","id":"ShutterContact","state":{"@type":"shutterContactState","value":"CLOSED"},"deviceId":"hdm:HomeMaticIP:3014F711A000009BB85DE504"}],"jsonrpc":"2.0"}

21:59:49.799 [DEBUG] [internal.devices.bridge.BridgeHandler] - Got update for hdm:HomeMaticIP:3014F711A000009BB85DE504
21:59:49.803 [DEBUG] [internal.devices.bridge.BridgeHandler] - Registered device: hdm:HomeMaticIP:3014F711A000009BB85DE504 - looking for hdm:HomeMaticIP:3014F711A000009BB85DE504
21:59:49.807 [DEBUG] [internal.devices.bridge.BridgeHandler] - Found child: org.openhab.binding.boschshc.internal.devices.windowcontact.WindowContactHandler@13e4c71 - calling processUpdate with {"@type":"shutterContactState","value":"CLOSED"}
21:59:49.812 [WARN ] [shc.internal.services.BoschSHCService] - Received invalid, expected type org.openhab.binding.boschshc.internal.services.shuttercontact.dto.ShutterContactServiceState
21:59:49.815 [DEBUG] [internal.devices.bridge.BridgeHandler] - Registered device: hdm:HomeMaticIP:3014F711A000005BB85A8E62 - looking for hdm:HomeMaticIP:3014F711A000009BB85DE504
21:59:49.817 [DEBUG] [internal.devices.bridge.BridgeHandler] - Registered device: hdm:HomeMaticIP:3014F711A000009BB85A3BD1 - looking for hdm:HomeMaticIP:3014F711A000009BB85DE504
21:59:49.820 [DEBUG] [internal.devices.bridge.BridgeHandler] - Registered device: hdm:HomeMaticIP:3014F711A000009BB85DE515 - looking for hdm:HomeMaticIP:3014F711A000009BB85DE504
21:59:49.822 [DEBUG] [internal.devices.bridge.BridgeHandler] - Registered device: roomClimateControl_hz_3 - looking for hdm:HomeMaticIP:3014F711A000009BB85DE504
21:59:49.825 [DEBUG] [internal.devices.bridge.BridgeHandler] - Registered device: hdm:HomeMaticIP:3014F711A000009BB85DE516 - looking for hdm:HomeMaticIP:3014F711A000009BB85DE504
21:59:49.828 [DEBUG] [internal.devices.bridge.BridgeHandler] - Registered device: hdm:HomeMaticIP:3014F711A000005BB85A776E - looking for hdm:HomeMaticIP:3014F711A000009BB85DE504
21:59:49.830 [DEBUG] [internal.devices.bridge.BridgeHandler] - Registered device: roomClimateControl_hz_5 - looking for hdm:HomeMaticIP:3014F711A000009BB85DE504
21:59:49.833 [DEBUG] [internal.devices.bridge.BridgeHandler] - Registered device: hdm:HomeMaticIP:3014F711A000009BB85DE544 - looking for hdm:HomeMaticIP:3014F711A000009BB85DE504
21:59:49.835 [DEBUG] [internal.devices.bridge.BridgeHandler] - Registered device: hdm:HomeMaticIP:3014F711A000005A185B996F - looking for hdm:HomeMaticIP:3014F711A000009BB85DE504
21:59:49.838 [DEBUG] [internal.devices.bridge.BridgeHandler] - Registered device: hdm:HomeMaticIP:3014F711A000191BB8583BC1 - looking for hdm:HomeMaticIP:3014F711A000009BB85DE504
21:59:49.841 [DEBUG] [internal.devices.bridge.BridgeHandler] - Registered device: hdm:HomeMaticIP:3014F711A000049BB85D3B36 - looking for hdm:HomeMaticIP:3014F711A000009BB85DE504
21:59:49.843 [DEBUG] [internal.devices.bridge.BridgeHandler] - Registered device: roomClimateControl_hz_4 - looking for hdm:HomeMaticIP:3014F711A000009BB85DE504

`

Only the warning shows that something is wrong. Unfortunately, I was not able to fix this error. What could be the reason?

I used the latest release (v1.1 test version).

Thanks for the support!

Sören

**Comment by coeing** [comment]
Hi @endsideX ,

Thanks for your report. Could you tell us what you expect? The fact that your devices are online is a good sign as this means that they are connected to your Bosch Smart Home Controller and openHAB :)

**Comment by endsideX** [comment]
Hi @coeing,
unfortunately, the status in OpenHab does not match the status in the smart home app or in reality. As you can see in the debug log, the status is reported correctly, but somehow not processed in my case. The status does not change.
This concerns especially the window contacts, the set temperature, and socket.

I would like to be able to use my Bosch devices in Openhab.

**Comment by endsideX** [comment]
The messages arrive, but they are of the wrong type. Here are some examples

<Incoming: "@type":"shutterContactState"
Expected: ShutterContactServiceState

Incoming: "@type":"powerMeterState" 
Expected: PowerMeterServiceState

Incoming: "@type":"powerSwitchState"
Expected: PowerSwitchServiceState

Incoming: "@type":"climateControlState"
Expected: RoomClimateControlServiceState>

I am using the latest firmware from April on my SHC ( 9.23.1937-18234). Maybe this is the reason.

**Comment by endsideX** [comment]
The problem was because I use openhab 3.0.1. I now use 3.0.0-SNAPSHOT and it works.

**Comment by coeing** [comment]
@endsideX I am glad that you found the reason for your problem! :) It looked strange as the message type is the expected one (e.g. ShutterContactServiceState has the identifier "shutterContactState"). @GerdZanker already merged the latest openHAB code into our repository, so our next official version will work with the latest openHAB version.

If you have any other problems, don't hesitate to open a new issue!

**Comment by csprang** [comment]
Dear all,

even I have some of the BOSCH and other Smart Home Equipment for a longer time, I'm quite new with Openhab. I like the Bosch Binding for openhab on my Raspi for implementation of more complex automation. 

As @endsideX I also have the problem, that the items of the Bosch Bindings are frozen after a while, so the status of the items is not changed anymore if the Bosch devices (inwall-switch, door-contacts, motion detectors etc.) are triggert outside the openhab-environment.

I use OH 3.1 and updated it twice without a success - while I'm looking for a solution, I found this blog and therefore left this comment. Unfortunately I'm still a beginner with openhab therefore I do not have much experiences with the internals ... but will improve ;-) 

Because this blog ist "closed" it looks, that there might already a solution for this frozen-phenomenea ... otherwise just the hint, that this occurs on OH 3.1

regards
Christoph
